name: Generate Directory Structure JSON

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-structure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Generate directory structure
      run: |
        python << EOF
        import os
        import json
        from functools import reduce

        def get_directory_structure(rootdir):
            dir = {}
            rootdir = rootdir.rstrip(os.sep)
            start = rootdir.rfind(os.sep) + 1
            for path, dirs, files in os.walk(rootdir):
                folders = path[start:].split(os.sep)
                subdir = dict.fromkeys(files)
                parent = reduce(dict.get, folders[:-1], dir)
                parent[folders[-1]] = subdir
            return dir

        structure = get_directory_structure('.')
        with open('directory_structure.json', 'w') as f:
            json.dump(structure, f, indent=2)
        EOF

    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add directory_structure.json
        git commit -m "Update directory structure JSON" || exit 0
        git push
